#cloud-config

runcmd:
  - sudo mkdir /root/.ssh/
  - sudo echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAr53uTiK0O/sbacgMcsHGp2mL0XvjpxI9O6n2KOPduFbmwKF/ZxLZm6nR1K6Dkj5aeg+BEFft1lrkh08ubJCYkF7/5vXy5dlzlLokCwc3aEOIIxD2WsOaFizmiy/b3KE16bvpkM7WzydlW6LyTaF3BoAikiw5D5IibroSij2mFWGVieXxXJSyryu+xmsNqGywuKc+4DjoaqEJJooBU53OdTkg8RGeN4dCrEWbJIc7agl5MDaBpL8aO6vH4OuGM7u3UFCTgDe6KRlK+bgYs4QEqb55RiNIp0vAOET4jH2QBhP489+5R1V6B/ozx2n0rDo3F3Hrha2Cp835KGoJVl2Gmw== rsa-key-20211028"  > /root/.ssh/authorized_keys2
  # Create a folder
  - mkdir actions-runner && cd actions-runner
  # Download the latest runner package
  - curl -o actions-runner-linux-x64-2.291.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.291.1/actions-runner-linux-x64-2.291.1.tar.gz
  # Optional: Validate the hash
  - echo "1bde3f2baf514adda5f8cf2ce531edd2f6be52ed84b9b6733bf43006d36dcd4c  actions-runner-linux-x64-2.291.1.tar.gz" | shasum -a 256 -c
  # Extract the installer
  - tar xzf ./actions-runner-linux-x64-2.291.1.tar.gz
  # allow run as root
  - export RUNNER_ALLOW_RUNASROOT="1"
  # Create the runner and start the configuration experience
  - ./config.sh --url https://github.com/runalsh/epam_again_aws --token AFBAYCPKHJU3IEK2T3X7VNLCOOPJG
# Last step, run it!
  - ./run.sh