version: "3.3"
networks:
  bridge:
    driver: bridge
volumes:
  local_pgdata:
  pgadmin-data:    
services:


  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", pg_isready -U pypostgres -d wandb ]
      timeout: 10s
      interval: 5s
      retries: 5
    volumes:
      - local_pgdata:/var/lib/postgresql/data  
    environment:
      # - POSTGRES_PASSWORD=${DB_PASSWORD}
      # - POSTGRES_USER=${DB_USER}
      # - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=pypostgres
      - POSTGRES_USER=pypostgres
      - POSTGRES_DB=wandb
    ports:
      - "5432:5432"
    networks:
      - bridge
      
     
  epamapp-front:
    build: ./frontnew/
    image: runalsh/epamapp-front:latest
    ports:
      - "80:80"
    depends_on:
      - epamapp-back
    links:
      - epamapp-back
    networks:
      - bridge
  
  
  epamapp-back:
    build: ./backnew/
    image: runalsh/epamapp-back:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_HOST=${DB_HOST}
      # - DB_NAME=${DB_NAME}  
      - DB_USER=pypostgres
      - DB_PASSWORD=pypostgres
      - DB_HOST=postgres
      - DB_NAME=wandb 
    links:
      - postgres
    networks:
      - bridge
 
 
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:6.4
  #   environment:
  #     # PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_EMAIL: 1@runalsh.ru
  #     # PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #     PGADMIN_DEFAULT_PASSWORD: runalsh
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   links:
  #     - postgres
  #   networks:
  #     - bridge