name: manual destroy infrastructure
on:
  workflow_dispatch:

jobs:
 tfdestroy:
   runs-on: ubuntu-latest
   defaults:
      run:
        working-directory: init
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
   steps:
      - name: send message to tg
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            *Commit message:* ${{ github.event.commits[0].message }}
            *Repository commit:*  https://github.com/${{ github.repository }}/commit/${{github.sha}}
            *WARNING:* TERRAFORM DESTROY INITIATED!
            *WARNING:* YOU HAVE 60 SECONDS TO CANCEL via WEB 
            *WARNING:* https://github.com/${{ github.repository }}/actions
          format: "markdown"
          disable_web_page_preview: true

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terraform                                                                      
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init  
        
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
